### ISSUE TITLE
San-serif should read sans-serif, that's what the spec is looking for

### ISSUE THREAD

**Issue by drkokandy** [learn-co-students/style-tag-and-h1-site-header-css-lab-abp-11-17#5]
I tried to submit a pull request with these changes to https://github.com/learn-co-students/style-tag-and-h1-site-header-css-lab-abp-11-17/pull/3 but I'm not sure how to de-tangle my edits to master from what the Learn IDE submitted as my assignment.

**Comment by aviflombaum** [comment]
Fixed in a8a1e7c
